version: "3"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
     - "5000:5000"
    volumes:
     - static-content:/uploads
    depends_on:
      - redis
      - db
  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
     - static-content:/uploads
    depends_on:
      - redis
  db:
    image: "postgres:9.6"
    env_file:
      - .env
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
volumes:
  static-content:
  dbdata: